services:
  db:
    image: mysql:8.0
    container_name: ikea-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: qvNv89gjIQ42
      MYSQL_DATABASE: ikea
      MYSQL_USER: ikea_user
      MYSQL_PASSWORD: DvQ113FmoXQt
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

volumes:
  mysql_data:

